variant = "loose"

[[issues]]
file = "src/BinPlugin.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/DependencyManagerType.php"
code = "semantics"
message = "Enums are only available in PHP 8.1 and above."
count = 1
